Exception in thread Thread-1 (worker):
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jeffhykin/repos/cool_cache/main/cool_cache/__init__.py", line 113, in worker
    pickle.dump((data.deep_hash, data.cache), cache_file, protocol=4)
AttributeError: Can't pickle local object 'named_list.<locals>.NamedList'
attempting wx import
attempting R import
R imported
[transit_tools:__enter__()] Starting ScatterPlot analysis 
[transit_tools:calc_gene_means()] Normalizing using: TTR 
/opt/homebrew/lib/python3.10/site-packages/pandas/core/internals/blocks.py:352: RuntimeWarning: divide by zero encountered in log10
  result = func(self.values, **kwargs)
[transit_tools:__exit__()] Finished ScatterPlot analysis in 2.3sec 
